---
- name: download jenkins repo
  get_url:
    url: "{{repo}}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: import key
  rpm_key:
    key: "{{key}}"
    state: present

- name: install jenkins
  yum:
    name: jenkins
    state: present

- name: start jenkins
  service:
    name: jenkins
    enabled: true
    state: started

